### ISSUE TITLE
Drop additional data in payload during validation?

### ISSUE THREAD

**Issue by reecefenwick** [trainiac/express-jsonschema#1]
I am wondering if data that is supplied in addition to the schema can be dropped?

Similar to mongoose where you can supply any data you want, but it will only store that which matches the schema.

Using the example from the README if I supply the following object:

```
{
    number: 12,
    name: 'Sycamore',
    type: 'Street',
    extra: 'Dodgy data'
}
```

How can I stop that extra property being passed to my controller with this module?

**Comment by trainiac** [comment]
I think you want to use the `additionalProperties` property in your schema.

`additionalProperties` -  Can be three things
    -  `false` to disallow any additional properties not in properties
    -   a sub-schema that all properties not included in properties must match
    -   a schema for all additional properties not included in properties

For example:

```
var StreetSchema = {
    type: 'object',
    properties: {
        number: {
            type: 'number',
            required: true
        },
        name: {
            type: 'string',
            required: true
        },
        type: {
            type: 'string',
            required: true
            enum: ['Street', 'Avenue', 'Boulevard']
        }
    },
    additionalProperties: false, // anything other property included other than name, type, or number is invalid
    additionalProperties: {  // additional properties are only valid if they are strings
        type: 'string' 
    },
    additionalProperties: { //  only apartmentNumber is an acceptable additional property and must be a number 
        apartmentNumber: {
            type: 'number'
        }
    }
}
```

This is the json-schema definition: http://json-schema.org/latest/json-schema-validation.html#anchor64

**Comment by reecefenwick** [comment]
Awesome thank you.
