### ISSUE TITLE
How to validate date-time property

### ISSUE THREAD

**Issue by reecefenwick** [trainiac/express-jsonschema#2]
In my payload I am looking to accept a UTC date time string to express an expiration date of the resource.

How do I specify that validation type?

Should I just accept a string and validate the string is a valid ISO 8601 date time myself?

Any advice and alternatives? Keeping the same error format as this module would be perfect

**Comment by reecefenwick** [comment]
Not an issue anymore as I implemented an easier to specify expiry time.

Still keen to know if "date-time" is a valid type

**Comment by trainiac** [comment]
It is a valid "format" as stated in the jsonschema spec http://json-schema.org/latest/json-schema-validation.html#anchor108.  The format is ISO 8601 standard date representation.  Here is an example of a schema you can use with express-jsonschema as well as some valid and invalid date time inputs:

``` js

// schema
{
    "type": "object", 
    "properties":{
        "date_mod": {
            "type": "string", 
            "format": "date-time", 
            "required": true 
        } 
    } 
}

// valid input
{
    "date_mod": "2015-07-05T19:04:17.413Z" // js Date objects have a toISOString() that generates this format
}

// invalid input
{
    "date_mod": "2015-07-05"  // has no time or timezone information, i.e. invalid ISO 8601
}
```

**Comment by reecefenwick** [comment]
Right I see what I was doing wrong. Thanks mate
