### ISSUE TITLE
Possible to use swagger defination as JSON schema?

### ISSUE THREAD

**Issue by rakesh1988** [trainiac/express-jsonschema#9]
Thanks for this wonderful library. I was wondering if it is possible to somehow convert a Swagger schema definition to something that we can use with this library. If, so can you please point me in the right direction

**Comment by trainiac** [comment]
Hi @rakesh1988 glad you are finding the library useful.  After taking a quick glance at Swagger it looks like they have their own schema structure so, unfortunately you will have find a way to transform your swagger param definitions to a valid json schema object. If you give me a more concrete example I could help you out.
